"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Currencies = function () {
    return (React.createElement("div", { className: "content" },
        React.createElement("div", { className: "container" },
            React.createElement("div", { className: "table-responsive" },
                React.createElement("table", { className: "table table-striped custom-table" },
                    React.createElement("thead", null,
                        React.createElement("tr", null,
                            React.createElement("th", { scope: "col" }, "Currency"),
                            React.createElement("th", { scope: "col" }, "Code"),
                            React.createElement("th", { scope: "col" }, "Convertation currency"),
                            React.createElement("th", { scope: "col" }, "Exchange rate"))),
                    React.createElement("tbody", null,
                        React.createElement("tr", null,
                            React.createElement("td", null, "1392"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "James Yates")),
                            React.createElement("td", null,
                                "Web Designer",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+63 983 0962 971"),
                            React.createElement("td", null, "NY University"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "4616"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Matthew Wasil")),
                            React.createElement("td", null,
                                "Graphic Designer",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+02 020 3994 929"),
                            React.createElement("td", null, "London College"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "9841"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Sampson Murphy")),
                            React.createElement("td", null,
                                "Mobile Dev",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+01 352 1125 0192"),
                            React.createElement("td", null, "Senior High"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "9548"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Gaspar Semenov")),
                            React.createElement("td", null,
                                "Illustrator",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+92 020 3994 929"),
                            React.createElement("td", null, "College"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "4616"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Matthew Wasil")),
                            React.createElement("td", null,
                                "Graphic Designer",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+02 020 3994 929"),
                            React.createElement("td", null, "London College"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "9841"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Sampson Murphy")),
                            React.createElement("td", null,
                                "Mobile Dev",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+01 352 1125 0192"),
                            React.createElement("td", null, "Senior High"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details"))),
                        React.createElement("tr", null,
                            React.createElement("td", null, "9548"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#" }, "Gaspar Semenov")),
                            React.createElement("td", null,
                                "Illustrator",
                                React.createElement("small", { className: "d-block" }, "Far far away, behind the word mountains")),
                            React.createElement("td", null, "+92 020 3994 929"),
                            React.createElement("td", null, "College"),
                            React.createElement("td", null,
                                React.createElement("a", { href: "#", className: "more" }, "Details")))))))));
};
exports.default = Currencies;
//# sourceMappingURL=Currencies.js.map